#!/bin/sh

# package name must be of lower case (a-z), digits (0-9) and (+-.)
NAME=$1
TARGET_VERNO=$2

mtype=`uname -m`
stype=`uname -s`
case  $stype  in
Linux  ) rel=`cat /proc/version | awk '{split($3,a,"."); b=a[1]a[2]; print b; }'`;
         export HOSTTYPE="linux$rel-$mtype" ;
         ;;
esac
export HOSTARCH=$HOSTTYPE
export HOSTARCH=i386

TARGET=`pwd`
TARGET_FN=${NAME}_${TARGET_VERNO}_${HOSTARCH}
PKGDIR=$TARGET/debpackage/${TARGET_FN}

# cleanup old stuff
rm -rf ${PKGDIR}

# copying content to package
make DESTDIR=${PKGDIR} install
#cp -r $TARGET/DEBIAN ${PKGDIR};

#If other maintainers, add them in "Uploaders:"
# Distribution (see debian/changelog):  stable, unstable, testing, frozen, experimental
# To make the library 1 single version installed only
# Includes the following 3 lines "Provides" "Conflicts" "Replaces"
#Provides: bufr-encoding-decoding
#Conflicts: bufr-encoding-decoding
#Replaces: bufr-encoding-decoding
# "Source" is for source package only, can be omitted if same as "Package"
#Source: $NAME
#Homepage: http://www.cmc.ec.gc.ca/bufr/t-abled
#Vcs-Svn: http://subversion.cmc.ec.gc.ca/repos/tabled/
#
# "Essential" must be "yes" when the package contains "shared libraries"

mkdir ${PKGDIR}/DEBIAN/
cat >> ${PKGDIR}/DEBIAN/control << EOF
Section: non-free/science
Priority: optional
Maintainer: Vanh Souvanlasy <Vanh.Souvanlasy@ec.gc.ca>
Package: $NAME
Version: ${TARGET_VERNO}
Architecture: ${HOSTARCH}
Essential: No
Depends: libc6-dev
Provides: $NAME
Conflicts: $NAME
Replaces: $NAME
Description: Environment Canada BUFR Library
EOF

cd debpackage

fakeroot dpkg -b $TARGET_FN

if [ -f ${TARGET_FN}.deb ]; then
	mv ${TARGET_FN}.deb ..
	echo "Created Debian package ${TARGET_FN}.deb"
	exit 0
fi

echo "Debian package creation failed!"
exit 1
