#!/bin/sh
#
# let autoreconf do everything for us: it will call
#         autoconf, autoheader,  aclocal, automake, libtoolize ...
#
echo "*** Running autoreconf"
rm -f configure
autoreconf --force --install
if [ -f configure ]; then
   echo "*** Done. You may now run configure"
else
	exit $?
fi

exit 0
